name: Code Freeze

on:
  workflow_dispatch:

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          ref: dev  
          token: ${{ secrets.GIT_TOKEN }}

      - run: git config user.name "rakeshkumar1019" && git config user.email "srakeshkumar1019@gmail.com"
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GIT_TOKEN }}
          commit-message: "Release ${{ github.sha }}"
          branch: dev
          base: main
          title: "Release: Merge dev into main"
          body: "This PR merges changes from dev into main."