name: Code Freeze

on:
  workflow_dispatch:
    inputs:
      rc:
        description: 'Release Candidate version eg(23.0.0-rc.1)'
        required: true
        type: string

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          ref: dev

      - run: git config user.name "rakeshkumar1019" && git config user.email "srakeshkumar1019@gmail.com"

      - name: Create a new branch
        run: |
          new_branch="code-freeze-${{ github.event.inputs.rc }}"
          git checkout -b $new_branch
          git push origin $new_branch
          echo "new_branch=$new_branch" >> $GITHUB_ENV

      - name: Authenticate GitHub CLI
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Create Pull Request
        run: |
          rc_version="${{ github.event.inputs.rc }}"
          gh pr create --base main --head $new_branch --title "Code Freeze: Merge $new_branch into main with RC=${rc_version}" --body "This PR merges changes from $new_branch into main."
