name: Code Freeze test

on:
  workflow_dispatch:

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          ref: dev

      - run: git config user.name "rakeshkumar1019" && git config user.email "srakeshkumar1019@gmail.com"
      
      - name: Authenticate GitHub CLI
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Create Pull Request
        id: create_pr
        run: |
          pr_output=$(gh pr create --base main --head dev --title "Release: Merge dev into main" --body "This PR merges changes from dev into main.")
          pr_number=$(echo "$pr_output" | grep -oP '(?<=#)\d+')
          echo "::set-output name=pr_number::$pr_number"
