name: Code Freeze test one
on:
  workflow_dispatch:
    inputs:
      rc:
        description: 'Release Candidate version eg(23.0.0-rc.1)'
        required: true
        type: string

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          ref: dev

      - run: git config user.name "rakeshkumar1019" && git config user.email "srakeshkumar1019@gmail.com"

      - name: Authenticate GitHub CLI
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Create Pull Request
        run: |
          rc_version="${{ github.event.inputs.rc }}"
          gh pr create --base main --head dev --title "Code Freeze: Merge dev into main with RC=${rc_version}" --body "This PR merges changes from dev into main."
