name: Main

on:
  push:
    branches:
      - dev

  # Manually trigger the workflow
  workflow_dispatch:

jobs:
  lint:
    uses: nuxeo/nuxeo-admin-console-ui/.github/workflows/lint.yaml@dev
    secrets:
      NPM_PACKAGES_TOKEN: ${{ secrets.NPM_PACKAGES_TOKEN }}
      GIT_TOKEN: ${{ secrets.GIT_TOKEN }} 

  test:
    uses: nuxeo/nuxeo-admin-console-ui/.github/workflows/utest.yaml@dev
    secrets:
      NPM_PACKAGES_TOKEN: ${{ secrets.NPM_PACKAGES_TOKEN }}
      GIT_TOKEN: ${{ secrets.GIT_TOKEN }} 

  build:
    needs: []
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - run: git config user.name "rakeshkumar1019" && git config user.email "srakeshkumar1019@gmail.com"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: ${{ env.NEXUS_URL }}
          scope: '@nuxeo'

      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: 'Update settings.xml with server configuration'
        run: |
          echo '<settings>
              <servers>
                <server>
                  <id>maven-internal</id>
                  <username>${{ secrets.PACKAGES_AUTH_USER }}</username>
                  <password>${{ secrets.PACKAGES_AUTH_TOKEN }}</password>
                </server>
              </servers>
              </settings>' > ~/.m2/settings.xml

      - name: Configure .npmrc
        working-directory: nuxeo-admin-console-web/angular-app
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GIT_TOKEN }}" >> .npmrc

      - name: Prepare Environment
        run: |
          echo "BRANCH_NAME=${GITHUB_HEAD_REF##*/}" >> $GITHUB_ENV
          pushd nuxeo-admin-console-web/angular-app
          echo $(npx -c 'echo "$npm_package_version"')
          echo "PACKAGE_VERSION=$(npx -c 'echo "$npm_package_version"')" >> $GITHUB_ENV 
          popd

      - name: Get Prerelease Version
        run: |
          git fetch --tags
          latest_tag=$(git tag -l 'v*.*.*-rc.*' --sort=-v:refname | head -n 1)
          
          if [[ $latest_tag =~ ^v([0-9]+\.[0-9]+\.[0-9]+)-rc\.([0-9]+) ]]; then
            base_version=${BASH_REMATCH[1]}
            rc_version=${BASH_REMATCH[2]}
            
            # Fetch tags that match the base version and beta pattern
            latest_beta_tag=$(git tag -l "${base_version}-beta.*" --sort=-v:refname | head -n 1)

            if [[ $latest_beta_tag =~ -beta\.([0-9]+) ]]; then
              beta_version=${BASH_REMATCH[1]}
              next_beta_version=$((beta_version + 1))
            else
              next_beta_version=0
            fi
            
            # Create the new tag without leading 'v'
            new_tag="${base_version}-beta.${next_beta_version}"
            echo "new_tag=$new_tag"
            echo "VERSION=$new_tag" >> $GITHUB_ENV
            
            echo "New prerelease tag: $new_tag"
          else
            echo "No rc tags found."
            exit 1
          fi

      
      - name: Update Version
        run: |
          # find . -type f -not -path "./node_modules/*" -regex ".*\.\(yaml\|sample\|json\)" -exec sed -i 's/'"${{env.PACKAGE_VERSION}}"'/'"${{env.VERSION}}"'/g' {} \;
          # set padded version to build package for connect preprod
          PADDED=$(printf '%03d' $(echo ${{env.VERSION}} | sed -r s/[0-9]+\.[0-9]+\.[0-9]+-beta\.\([0-9]+\)/\\1/g))
          PADDED_VERSION=$(echo ${{env.VERSION}} | sed -E "s/([0-9]+\.[0-9]+\.[0-9]+-beta\.)[0-9]+/\\1$PADDED/g")
          echo "PADDED_VERSION=$PADDED_VERSION" >> $GITHUB_ENV
          find . -type f -not -path "./node_modules/*" -regex ".*\.\(xml\)" -exec sed -i 's/'"${{env.PACKAGE_VERSION}}"'/'"$PADDED_VERSION"'/g' {} \;
          sed -i -e 's/\${project.version}/'"$PADDED_VERSION"'/g' nuxeo-admin-console-package/pom.xml
          pushd nuxeo-admin-console-web/angular-app
          npm version ${{env.VERSION}} --no-git-tag-version
          popd
         
      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Install Dependencies
        working-directory: nuxeo-admin-console-web/angular-app
        run: npm install

      - name: Restore Maven cache
        uses: skjolber/maven-cache-github-action@v1
        with:
          step: restore

      - name: Build Angular Project
        run: mvn package

      - name: Save Maven cache
        uses: skjolber/maven-cache-github-action@v1
        with:
          step: save

      - name: Archive Package
        uses: actions/upload-artifact@v4
        with:
          name: packages
          path: |
            nuxeo-admin-console-package/target/nuxeo-admin-console-test-*.zip

      - name: Delete & Update .npmrc 
        working-directory: nuxeo-admin-console-web/angular-app
        run: |
          rm .npmrc
          echo "
          @hylandsoftware:registry=https://npm.pkg.github.com
          @nuxeo:registry=https://packages.nuxeo.com/repository/npm-public
          registry=https://registry.npmjs.org/
          " >> .npmrc

      - name: Tag
        run: |
          git add nuxeo-admin-console-web/angular-app/package-lock.json
          git commit -a -m "Release ${{env.VERSION}}"
          git tag -a v${{env.VERSION}} -m "Release ${{env.VERSION}}"
          git push origin v${{env.VERSION}}
        
      - name: Publish on Pre-Prod Marketplace
        working-directory: nuxeo-admin-console-package/target
        env:
          CONNECT_PREPROD_URL: https://nos-preprod-connect.nuxeocloud.com/nuxeo
        run: |
          PACKAGE="nuxeo-admin-console-test-${{env.PADDED_VERSION}}.zip"
          STATUS_CODE=`curl -i --silent --output publish-req.output -w "%{http_code}" -u "${{ secrets.CONNECT_PREPROD_AUTH }}" -F package=@$PACKAGE "$CONNECT_PREPROD_URL/site/marketplace/upload?batch=true"`
          cat publish-req.output
          if [[ "$STATUS_CODE" != "200" ]]
          then
            exit 1
          else
            exit 0
          fi

      # - name: Publish on Pre-Prod Marketplace
      #   working-directory: nuxeo-admin-console-package/target
      #   env:
      #     CONNECT_PREPROD_URL: https://nos-preprod-connect.nuxeocloud.com/nuxeo
      #   run: |
      #     PACKAGE="nuxeo-admin-console-${{env.PADDED_VERSION}}.zip"
      #     ls
      #     echo "PACKAGE=$PACKAGE" >> $GITHUB_ENV
      #     echo $PACKAGE