name: Code Freeze
on:
  workflow_dispatch:

jobs:
  get-latest-beta-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          ref: dev

      - run: git config user.name "rakeshkumar1019" && git config user.email "srakeshkumar1019@gmail.com"

      - name: Authenticate GitHub CLI
        run: |
          echo "${{ secrets.GIT_TOKEN }}" | gh auth login --with-token 

      - name: Get latest beta tag
        run: |
          git fetch  origin --tags
          latest_beta_tag=$(git for-each-ref --sort=-taggerdate --format '%(refname:short)' refs/tags | grep -E '^v23\.[0-9]+\.[0-9]+-beta\.[0-9]+$' | head -n 1 | sed 's/^v//')
          echo "Latest beta tag: $latest_beta_tag"
          echo "LATEST_BETA_TAG=$latest_beta_tag" >> $GITHUB_ENV

      - name: Add Markdown to Summary
        run: |
            echo '# Latest Beta Tag' >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
            echo "${{ env.LATEST_BETA_TAG }}" >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY

     